### PR TITLE
Adding user sign in api to api design

### PR DESCRIPTION
**Pull request by mohammadibrahemmustafa**

### CODE REVIEW

**Comment by haithamalnaeb** [comment]
Thank you @mohammadibrahemmustafa for this PR

I have a quick feedback to improve it:

- The end point should be renamed from "/signup", to "/user", so we can have POST, GET, PATCH, PUT /user, as in [petstore](https://editor.swagger.io/) example, I suggest PATCH for user sign in
- It would be easier for fronend developers if we used requestBody content as application/x-www-form-urlencoded instead of application/json, you can then test it using form inputs
- please use camelCase, like countryId instead of country_id, as in [petstore](https://editor.swagger.io/) example
- please add the main details about properties, like maxlength or pattern, depending on property type, in vs code you can use CTL + . to quick fix it, you need openApi extension to be installed first
- it would be better to use 400 instead of "400" for response code 
- before submit your pull request, make an audit test, using the openApi extension (click on purple icon to the top right), keep the score over 50 out of 100 :) 😊

I hope doing this will move your code to the next level 👍

**Comment by mohammadibrahemmustafa** [comment]
@haithamalnaeb Thank you for your review. I have adjusted the commit and I got 55 score on the vs code extenstion.

**Comment by haithamalnaeb** [comment]
@mohammadibrahemmustafa
You did a great job 👍

almost done

the only issue is that we need to return token on success sign in, not otpToken

also if you add `additionalProperties: false` in both request and response schema and `maxLength: 32` to response token will increase the security score to over 60
finally, for password pattern, you should set the minimum to 8, so use `^.{1,50}$` instead of `^.{8,50}$`

**Comment by mohammadibrahemmustafa** [comment]
Thank you for your review. I have adjusted the files again. This time I got 69

**Comment by haithamalnaeb** [comment]
You did amazing contribution here @mohammadibrahemmustafa 

I hope you gain good experience, keep it going

**Pull request merged**
