### PR TITLE
[API design] #26 - Create product model

### LINKED ISSUE #26: [API design] Create Product Model
This model should contain:

 - title
 - details
 - main photo
 - category id
 - owner id
 - area id
 - tags
 - views
 - status (number)
 - created at
 - updated at

### PR DESCRIPTION
**Pull request by yaser-alazm**

### CODE REVIEW

**Comment by yaser-alazm** [comment]
Couldn't link the PR to it's related issue [here](https://github.com/HibatApp/hibat-backend/issues/26)

**Comment by haithamalnaeb** [comment]
Thank you @yaser-alazm for this PR, it is an important one.

In general your PR is good, you put some great effort in here 👍
there are some notes to improve it more:
- for title,details,tags, the pattern better be something like `^.{0,200}$` , as the title might be written in many non-Latin characters, so we cannot limit it to `a-zA-Z0-9` thus we used `.`
- try to add maxLength for the patterns when applicable, like in title, details tags, by adding {min,max} at the end
- maxLength and pattern are not applicable to integer, instead you can add minimum:0, maximum: 99999, format: int32
- categoryId, ownerId, areaId should be integer, no need for reference.
- I noticed you contributed to other tasks in this PR (you added Category and Location model), try to focus on one task in each commit, the other can be added later, so if we had to revert this commit, we don't lose stuff in other places.

Most of this notes can be detected and bulk fixed by performing audit test like in the screenshot

image

**Comment by yaser-alazm** [comment]
@haithamalnaeb 
> for title,details,tags, the pattern better be something like ^.{0,200}$
> maxLength and pattern are not applicable to integer, instead you can add minimum:0, maximum: 99999, format: int32
> categoryId, ownerId, areaId should be integer, no need for reference.

All been pushed :+1: 

 > try to add maxLength for the patterns when applicable, like in title, details tags, by adding {min,max} at the end

This already been added in the original commits 

> I noticed you contributed to other tasks in this PR

Actually I just declared the type of each model just to use it as a reference to `categoryId` & `areaId`, but since we don't use references here so all removed

**Comment by haithamalnaeb** [comment]
All good,
great job

**Pull request merged**
