### PR TITLE
add get user path doc

### PR DESCRIPTION
**Pull request by yaser-alazm**
Adding get user path api doc

### CODE REVIEW

**Comment by haithamalnaeb** [comment]
Good PR @yaser-alazm 

This request is to get current user info, so we don't need userId, as we already know him from token.

Later on... in another task, when we need to get other users profile, userId should be in path, as query usually used for optional parameters.

**Comment by yaser-alazm** [comment]
Thanks @haithamalnaeb, 
Updated

**Comment by haithamalnaeb** [comment]
All looks good 👍

my bad, I forget to tell you about authorization


It would great if you add:
put > **security>  - bearerAuth: []**

As this one for signed in users only

**Comment by yaser-alazm** [comment]
@haithamalnaeb 
Both PR's already updated :+1:

**Pull request merged**
