### PR TITLE
User sign up

### PR DESCRIPTION
**Pull request by KaramNassar**

### CODE REVIEW

**Comment by haithamalnaeb** [comment]
Thank you @KaramNa for this PR

I have a quick feedback to improve it:

- The end point should be renamed from "/signup", to "/user", so we can have POST, GET, PATCH, PUT /user, as in [petstore](https://editor.swagger.io/) example
- It would be easier for fronend developers if we used requestBody content as application/x-www-form-urlencoded instead of application/json, you can then test it using form inputs
- please use camelCase, like fullName instead of full_name, as in [petstore](https://editor.swagger.io/) example
- please add the main details about properties, like maxlength or pattern, depending on property type, in vs code you can use CTL + . to quick fix it, you need openApi extension to be installed first
- after finish, try to format the code (it will auto remove blank lines you added)
- before submit your pull request, make an audit test, using the openApi extension (click on purple icon to the top right), keep the score over 50 out of 100 😊

I hope doing this will move your code to the next level 👍

**Comment by haithamalnaeb** [comment]
Great job, 

To make the response readable for frontend app, we need to response in json,

kindly convert response to application/json
and wrap the string with object that has proprieties otpToken
responses > 200 > content > application/json > schema > type: object > properties >  otpToken > type: string


Also, try to improve your RegEx:
- fullName: ^.{1,50}$     (any character even if non-Latin, example Arabic, between 1 and 50 in length)
- mobile: ^[0-9]{8,14}$ (between 8 and 14)
- password: ^.{1,50}$  (any character, even non-Latin)
- otpToken: ^[0-9a-z]{32}$
- countryId: adding maximum: 200 will help the score, there are no more than 200 countries in the world

Pro tip: adding "example:" will help validate your pattern

**Comment by haithamalnaeb** [comment]
Dear @KaramNa 
kindly resubmit your PR

**Comment by KaramNassar** [comment]
Thanks for your feedback and tips, I just made another pull request, I don't know if that's how I resubmit my PR, sorry if that's a wrong way.

**Comment by haithamalnaeb** [comment]
It is ok, I merged this one and manually copied your other PR, because it was conflicted with `/user put` request

Thank you for your contribution, you are listed in the contributors page,
however, if your photo does not appear on main page, confirm that the email you are committing from (in your IDE setting), is listed in your gitHub account, you can do this by this command `git config --get user.email`

**Comment by KaramNassar** [comment]
Thank you for giving us this opportunity

**Pull request merged**
