### PR TITLE
Delete from Wishlist

### PR DESCRIPTION
**Pull request by Ammar-Alhamwi**

### CODE REVIEW

**Comment by haithamalnaeb** [comment]
Thanks for PR

I have the following feedback:
- the endpoint should be /wishlist/{productId}
- the method should be `delete` instead of `get`
- try to introduce a new group, setting `tags` to wishlist
- `get` method cannot have requestBody
- add the `productId` as path parameter, not in requestBody (refer to [Petstore example](https://editor.swagger.io/))
- use `200` instead of `'200'` for response code
- use `401` instead of `400` for invalid token, (http code [explained here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes))

**Comment by Ammar-Alhamwi** [comment]
Thank you for your reply, it has been modified. Please review again

**Comment by haithamalnaeb** [comment]
Thank you,
much better

spoiler alert, big amount of experience coming!

kindly change endpoint from `/api/delete/{id}` to `/wishlist/{productId}`
Also you don't have to use quota in yaml in most cases, so lets remove it everywhere
please add tags: 
- wishlist

in id > schema: you can add:
 `           maximum: 999999
            minimum: 0
            format: int32`
to have better understanding and better score
you can also add it by:
- perform security audit, by clicking on the purple icon to the top right (if you installed openApi extension)
- setting mouse pointer on schema
- Ctrl + .
- select Add maximum, minimum, format properties 
image


finally, this requested for authorized users only, so please add this:
in delete > security> - bearerAuth: []

like the /user get request

I hope you understand why we added every line, you can ask if you missed any point

**Comment by Ammar-Alhamwi** [comment]
Thank you for the notes, it helped me
This is my first time using openapi
So I learned a lot of things
Please review and let me know if there are any mistakes

**Comment by haithamalnaeb** [comment]
Great job, all looks good,

Thanks you

**Pull request merged**
